import { Toaster } from '@/components/ui/toaster'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        {/* <NavigationBar /> */}
        {/* <Modals /> */}
        {children}
        <Toaster />
      </body>
    </html>
  )
}
