import { Modals } from '@/components/Modals/Modals'
import { TopBar } from '@/components/TopBar/TopBar'
import { Footer } from '@/components/Footer/Footer'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={inter.className} suppressHydrationWarning>
      <body>
        <TopBar />

        {/* <NavigationBar /> */}

        {children}

        <Footer />
        <Modals />

        <Toaster />
      </body>
    </html>
  )
}
